### ISSUE TITLE
gen: operationId duplicate in additional_bindings case

### ISSUE THREAD

**Issue by sashamelentyev** [ogen-go/protoc-gen-oas#60]
```prototext
  service: {
    name: "Service"
    method: {
      name: "GetMethod"
      input_type: "Request"
      output_type: "Response"
      options: {
        [google.api.http]: {
          get: "/api/v1/{id}",
          additional_bindings {
            get: "/api/v1/{id}/search/{query}"
          }
        }
      }
    }
  }
```
Final result duplicate operationId. operationId must be unique
```yaml
paths:
    /api/v1/{id}:
        get:
            operationId: getMethod
...
    /api/v1/{id}/search/{query}:
        get:
            operationId: getMethod
...
```
